"""Validate the {{title}}.

Generated by TechMachine's satellite template. Records are checked one at a
time rather than loaded into a list first, so the check scales to catalogs of
any size (game-catalog validates ~1M records in about 90 seconds on CI).

Run with: python -m app.validate
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "{{category}}"

REQUIRED = {"slug", "name", "source_urls", "verified"}
DATE_FIELDS = {{date_fields}}
RANGES = {{ranges}}  # field -> (low, high), inclusive
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
MAX_ERRORS = 200  # a wall of identical errors helps nobody


def _check(rel: str, rec: dict[str, Any], errors: list[str]) -> None:
    missing = REQUIRED - rec.keys()
    if missing:
        errors.append(f"{rel}: missing required field(s) {sorted(missing)}")

    slug = rec.get("slug")
    if isinstance(slug, str) and not SLUG_RE.match(slug):
        errors.append(f"{rel}: slug '{slug}' is not kebab-case")

    urls = rec.get("source_urls")
    if not isinstance(urls, list) or not urls:
        errors.append(f"{rel}: source_urls must be a non-empty list")
    elif not all(isinstance(u, str) and u.startswith("http") for u in urls):
        errors.append(f"{rel}: every source_url must be an http(s) string")

    for field in DATE_FIELDS:
        value = rec.get(field)
        if value is not None and not (isinstance(value, str) and DATE_RE.match(value)):
            errors.append(f"{rel}: {field} '{value}' is not YYYY-MM-DD")

    for field, (low, high) in RANGES.items():
        value = rec.get(field)
        if value is None or isinstance(value, bool):
            continue
        if not isinstance(value, (int, float)) or not low <= value <= high:
            errors.append(f"{rel}: {field} {value!r} outside {low}-{high}")


def validate(data_dir: Path = DATA) -> list[str]:
    errors: list[str] = []
    seen: dict[str, str] = {}
    count = 0

    for path in sorted(data_dir.rglob("*.json")):
        rel = path.relative_to(data_dir.parent).as_posix()
        count += 1
        try:
            rec = json.loads(path.read_text(encoding="utf-8-sig"))
        except json.JSONDecodeError as exc:
            errors.append(f"{rel}: invalid JSON ({exc})")
            continue
        if not isinstance(rec, dict):
            errors.append(f"{rel}: top level must be an object")
            continue

        _check(rel, rec, errors)

        slug = rec.get("slug")
        if isinstance(slug, str):
            if slug in seen:
                errors.append(f"{rel}: duplicate slug '{slug}' (first seen in {seen[slug]})")
            else:
                seen[slug] = rel
            if path.stem != slug:
                errors.append(f"{rel}: filename does not match slug '{slug}'")

        if len(errors) >= MAX_ERRORS:
            errors.append(f"... stopped after {MAX_ERRORS} errors")
            break

    if count == 0:
        errors.append(f"no {{category}} records found under {data_dir}")
    return errors


def main() -> int:
    errors = validate()
    for error in errors:
        print(error)
    if errors:
        print(f"FAIL: {len(errors)} problem(s)")
        return 1
    print("OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
